### ISSUE TITLE
Problem with media-type in chapters?

### ISSUE THREAD

**Issue by macaju** [victor-o-silva/game-programming-patterns-epub#3]
I'm not sure if this is a script issue or maybe calibre issue.

When converting the generated epub to any other format with calibre, calibre always ends with the following error. I manage to converted changing some things in the **content.opf**.

- The error:

> Parsing all content...
Parsing EPUB/nav.xhtml ...
The item EPUB/s00_c00.htmlx is not a XML document. Removing it from spine.
The item EPUB/s00_c01.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c00.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c01.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c02.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c03.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c04.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c05.htmlx is not a XML document. Removing it from spine.
The item EPUB/s01_c06.htmlx is not a XML document. Removing it from spine.
The item EPUB/s02_c00.htmlx is not a XML document. Removing it from spine.
The item EPUB/s02_c01.htmlx is not a XML document. Removing it from spine.
The item EPUB/s02_c02.htmlx is not a XML document. Removing it from spine.
The item EPUB/s02_c03.htmlx is not a XML document. Removing it from spine.
The item EPUB/s03_c00.htmlx is not a XML document. Removing it from spine.
The item EPUB/s03_c01.htmlx is not a XML document. Removing it from spine.
The item EPUB/s03_c02.htmlx is not a XML document. Removing it from spine.
The item EPUB/s03_c03.htmlx is not a XML document. Removing it from spine.
The item EPUB/s04_c00.htmlx is not a XML document. Removing it from spine.
The item EPUB/s04_c01.htmlx is not a XML document. Removing it from spine.
The item EPUB/s04_c02.htmlx is not a XML document. Removing it from spine.
The item EPUB/s04_c03.htmlx is not a XML document. Removing it from spine.
The item EPUB/s05_c00.htmlx is not a XML document. Removing it from spine.
The item EPUB/s05_c01.htmlx is not a XML document. Removing it from spine.
The item EPUB/s05_c02.htmlx is not a XML document. Removing it from spine.
The item EPUB/s05_c03.htmlx is not a XML document. Removing it from spine.
The item EPUB/s05_c04.htmlx is not a XML document. Removing it from spine.
Python function terminated unexpectedly
  Spine is empty (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1099, in run
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1292, in create_oebbook
  File "site-packages\calibre\ebooks\oeb\reader.py", line 72, in __call__
  File "site-packages\calibre\ebooks\oeb\reader.py", line 703, in _all_from_opf
  File "site-packages\calibre\ebooks\oeb\reader.py", line 348, in _spine_from_opf
calibre.ebooks.oeb.base.OEBError: Spine is empty

> 

- The modification in **content.opf** to get it working with calibre convertions:

> media-type="application/octet-stream" -> media-type="application/xhtml+xml"

**Comment by macaju** [comment]
I guess it should be this `content = soup.select('div.content')[0]` that its not "application/xhtml+xml" and we need to set the media-type.

**Comment by macaju** [comment]
I made a PR, see #4

**Comment by victor-o-silva** [comment]
I just merged the PR.

Thanks a lot for it!
